language: python
dist: trusty
sudo: false

python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes
- conda update -q conda
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip openblas numpy scipy
- source activate test-environment
- "pip install -q --upgrade 'pip'"
- "pip install -q 'coverage'"
- "pip install -q 'pytest-cov'"
- "pip install -q 'codacy-coverage'"
- "pip install -qr requirements.txt"
- "pip install -q coveralls"
- "pip install -q ."
- "cd tools/friedchicken && pip install -q ."
install:
- "echo done"

# command to run tests, e.g. python setup.py test
script:
- pytest --cov=laserchicken --cov-report xml:coverage.xml

after_script:
- python-codacy-coverage -r coverage.xml
- coveralls
